language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
- pip install pylint
script:
- pylint eoq_calculator.py
- python eoq_calculator_tests.py -v
deploy:
  provider: heroku
  app: powerful-ocean-42757
  on: master
  api_key:
    secure: Ae/m8KRsqxRp4yEHzxk6BfkskXo+OStIMAAlTeOHeCKQZcjnrK3kLD63qucvYvSzoi6MCz5hg5YiQZz6bUHBFZq45vqx8+uoHTkA/4eGUEjqPmkXgFjsLjDeB1I0SbvAXZOYytoq5UPzxNLkiwsdm5c6nm7VKnaU2wHQ5d3kff1QhIIq5lg9qpVhIk7bxyngewh9FaNXhoCPzrD5fIF8iqiokENc0oUWaAD2pPgEB9wteeQkJ6lJxM49sEfP+JUOuiDZTa7X30ETDxIVCfYZpYhBZMyDV5YBBeCf3Uux+oGupBaT4dnJQ/XqQ/TmWZopBcsMT2JOKamdFoYCkQSQmpduJ0Aw09oucUGKbImnalS0Gzzq6H59Cu2yPLcNi7JaAtV7uw123bSpGXjuuBCOk7ZO3bxMLHlhkoYptvFhmJFZqvHFoBkJFLMOqpRb/t8er1qutgQ3q1Lotf1wlHlP19UWySblYagwiKYGI+2X6SDwg+ZucsiapDasUPZXwmmmmhxGZafwyeb5iaGp+MCgPuFJF6jyAjfkoqFEsDAG2K5eKKABTYrxzn2gXsL0wICCVOvnK5vTTpA50yA8bMlnpDKCLjlnQ0gJ+qWArWT/EJv42lygZ+g594WCjTj/N0Zu7jGJBc+SnVcYxM74V+g48jbwLX4l3BKMhyxn0MrcQXg=
