language: python
python:
    - "3.7"
install:
    - pip install -r requirements.txt
    - pip install pylint
script:
    - pylint eoq_calculator.py
    - python eoq_calculator_tests.py -v
deploy:
    provider: heroku
    api_key: test
    app: powerful-ocean-42757
    on: master

